image: Visual Studio 2017

before_build:
  - gitversion /l console /output buildserver

build_script:
  - ps: src\build.ps1 $env:GitVersion_NuGetVersion
  - ps: release\build.ps1 $env:GitVersion_NuGetVersion -GitHubRelease:$($env:APPVEYOR_REPO_TAG -eq "true")

artifacts:
  - path: release\*.xml
  - path: release\*.tar.gz

deploy:
  - provider: Environment
    name: GitHub Releases
    on:
      appveyor_repo_tag: true
